language: go
sudo: false
go:
  - 1.6
  - 1.7
  - 1.8
  - tip
matrix:
  allow_failures:
    - go: 1.6
    - go: tip
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
install:
  - glide install
  - cd edgegrid/json && go install . && cd ../ && go install .
script:
  - export PATH="$PATH:$HOME/gopath/bin"
  - cp $HOME/gopath/src/github.com/akamai-open/AkamaiOPEN-edgegrid-golang/sample_edgerc $HOME/.edgerc
  - go test -v ./
