language: go
sudo: false
go_import_path: github.com/akamai-open/AkamaiOPEN-edgegrid-golang
go:
  - 1.6
  - 1.7
  - 1.8
  - tip
matrix:
  allow_failures:
    - go: 1.6
    - go: tip
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
install:
  - glide up
script:
  - export PATH="$PATH:$HOME/gopath/bin"
  - cd edgegrid && go test -v -race ./...
